language: python
python:
  - "3.4"
install:
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source=. tests.py
branches:
  only:
    - master

after_success:
  - coveralls
